use_frameworks!
platform :ios, '10.0'
#source 'https://github.com/JJson/NextLevel.git'
target 'PCVisionPicker_Example' do
  pod 'PCVisionPicker', :path => '../'

end
target 'PCVisionPicker' do
    pod 'NextLevel', :git => 'https://github.com/JJson/NextLevel.git', :tag => '0.16.4.JJ'
end

